# Generated by Django 5.0.4 on 2024-05-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('channel_url', models.URLField(blank=True)),
                ('personal_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='Write your description....', null=True)),
                ('image', models.ImageField(default='default_image.png', upload_to='images/')),
            ],
        ),
    ]
