# Generated by Django 5.0.4 on 2024-05-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_linkprofile_created_at_linkprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkprofile',
            name='personal_url',
            field=models.CharField(max_length=200),
        ),
    ]
