ICON_MAP = {
    'spotify': 'channel/spotify-icon.png',
    'playlist': 'channel/playlist-icon.png',
    'applemusic': 'channel/apple-music-icon.png',
    'youtube': 'channel/youtube-play-icon.png',
    'instagram': 'channel/instagram-icon.png',
    'snapchat': 'channel/snapchat-icon.png',
    'twitter': 'channel/x-icon.png',
    'facebook': 'channel/facebook-icon.png',
    'linkedin': 'channel/linkedin-icon.png',
    'tiktok': 'channel/tik-tok-icon.png',
    'soundcloud': 'channel/sound-cloud-icon.png',
    'reddit': 'channel/reddit-icon.png',
    'medium': 'channel/medium-icon.png',
    'twitch': 'channel/twitch-icon.png',
    'website': 'channel/website-icon.png',
    'phone': 'channel/phone-icon.png',
    'email': 'channel/email-icon.png',
    'customlink': 'channel/default-icon.png',
}
